### ISSUE TITLE
server error with python client

### ISSUE THREAD

**Issue by AM1648** [SharifAIChallenge/AIC18-Server#2]
python client, any map, error on server:

Exception in thread "Thread-2" java.lang.NoClassDefFoundError: javafx/util/Pair
        at GameEngine.parseUnitCreationData(GameEngine.java:403)
        at GameEngine.simulateEvents(GameEngine.java:205)
        at server.core.GameServer$Loop.lambda$run$0(GameServer.java:192)
        at server.core.GameServer$Loop.run(GameServer.java:275)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more

client output:
Trying to connect #1
connected to server!
turn number 1:

**Comment by Naghipourfar** [comment]
Hi,
Did you run the jar file? 
if yes, please install `java-openjfx` through your package manager(or whatever means you used to install Java on your machine). Note that `java-openjfx` is compatible with OpenJDK8, not previous versions. 
otherwise, please run with jar through your terminal using command `java -jar AIC18-Server.jar` and see the server output. let us know if the same exception throws again.

**Comment by Naghipourfar** [comment]
If you're using linux, try this:
`sudo apt-get install java-openjfx`
