### ISSUE TITLE
IO exception in connecting client

### ISSUE THREAD

**Issue by nekooei** [SharifAIChallenge/AIC18-Server#4]
after 2 client connected to server server start to showing Exceptions

`Info (ClientHandler): message receiving failure
java.io.IOException: EOF reached.
	at network.JsonSocket.get(JsonSocket.java:150)
	at server.network.ClientHandler.receive(ClientHandler.java:225)
	at server.network.ClientHandler.lambda$getReceiver$1(ClientHandler.java:195)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by nekooei** [comment]
clients are C++

**Comment by Naghipourfar** [comment]
"EOF reached" means the game is finished!

**Comment by nekooei** [comment]
It's better to close server or showing something meaningful messages, isn't that?
anyway thanks for replying :) :+1:
